FROM python:3.12-slim
WORKDIR /app

COPY common/ ./common/
COPY stock_trader/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY stock_trader/ ./stock_trader/

ENV PYTHONPATH=/app

WORKDIR /app/stock_trader
CMD ["python", "main.py"]
